name: Test
on:
  pull_request:
    paths:
      - '**'
      - '!**.md'
      - '!LICENSE'
  push:
    branches: [ main ]
    paths:
      - '**'
      - '!**.md'
      - '!LICENSE'

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2.5.0 # v2.5.0

      - name: Setup Go
        uses: actions/setup-go@v3.3.1 # v3.3.1
        with:
          go-version: '1.18'

      - name: Bootstrap tools
        run: make bootstrap-tools

      - name: Run linters
        run: make lint

      - name: Run tests
        run: make test
